### ISSUE TITLE
update grunt-cep dependency to 3.0

### ISSUE THREAD

**Issue by jDmacD** [fcamarlinghi/grunt-init-cep#3]
Hi,
related to [this issue](https://github.com/fcamarlinghi/grunt-cep/issues/4) in grunt-cep.

``` json
{
    "devDependencies": {
        "grunt-cep": "~0.2.0"
    }
}
```

**Comment by fcamarlinghi** [comment]
Fixed by merging your pull request #4 and by publishing grunt-cep 0.3.0 to NPM.
