### ISSUE TITLE
Wont launch PPRO 2015.3 and AE.

### ISSUE THREAD

**Issue by jimmic** [fcamarlinghi/grunt-init-cep#7]
Will grunt cep be updated to package up and launch the latest releases by Adobe?

**Comment by fcamarlinghi** [comment]
Hello, discussion about supporting the latest Adobe release is ongoing [in this issue](https://github.com/fcamarlinghi/grunt-cep/issues/15) on the main grunt-cep repository. I'll close this issue in favor of that one.
